kubernetesClusterDomain: cluster.local

serviceCoder:
  name: coder-service

serviceOnDemand:
  name: on-demand-service

common:
  namespace: petar

deploymentCoder:
  name: coder
  replicas: 1
  appLabel: coder
  serviceAccountName: coder-admin
  container:
    name: coder
    image: ghcr.io/coder/coder:latest
    port: 7080
    env:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ENVPROXY_ACCESS_URL: "http://localhost:7080"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

deploymentOnDemand:
  name: on-demand
  replicas: 1
  appLabel: on-demand
  container:
    name: on-demand
    image: ghcr.io/austriandatalab/terraform-deployment-automation/on_demand:latest
    port: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"