# Use an official Python runtime as a parent image
FROM python:3.12-alpine

# Set the working directory in the container
WORKDIR /usr/src

# Copy the current directory contents into the container at /usr/src/app
COPY app.py /usr/src
COPY requirements.txt /usr/src
COPY main.tf /usr/src
COPY test_app.py /usr/src

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN wget https://get.opentofu.org/install-opentofu.sh -O install-opentofu.sh

# Give it execution permissions:
RUN chmod +x install-opentofu.sh

# Please inspect the downloaded script

# Run the installer:
RUN ./install-opentofu.sh --install-method apk

# Remove the installer:
RUN rm install-opentofu.sh
