version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-demo-app
    networks:
      - flask-app-net
    ports:
      - 5050:5000
    healthcheck:
      test: wget --quiet --tries=3 --spider http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  flask-app-net:
    driver: bridge

volumes:
  mongodb: {}