apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://rancher.caas-0025.dev.austrianopencloudcommunity.org/k8s/clusters/local"

users:
- name: "local"
  user:
    token: "kubeconfig-u-wuml4xpgsk9rmnp:lvhsqfv5m82frkdnpg45gwgmjqpnmcjt7dr6dhl4t2r6g7v4xfvrvl"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
