apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: {{.Values.common.namespace }}  
  annotations:
    spec.ingressClassName: "gce"
    kubernetes.io/ingress.regional-static-ip-name: "ood-ip"
spec:
  defaultBackend:
    service:
      name: on-demand-service
      port:
        number: 80
