---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceOnDemand.name }}
  namespace: {{ .Values.common.namespace }}  
  labels:
    app.kubernetes.io/name: {{ .Values.serviceOnDemand.name }}
  #annotations:
    #cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.deploymentOnDemand.container.port }}
    protocol: TCP
    targetPort: {{ .Values.deploymentOnDemand.container.port }}
  selector:
    app: {{ .Values.deploymentOnDemand.appLabel }}
