apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
  namespace: petar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder
  template:
    metadata:
      labels:
        app: coder
    spec:
      containers:
      - name: coder
        image: ghcr.io/coder/coder:latest  # Replace with your specific version
        env:
        - name: CODER_HTTP_ADDRESS
          value: "0.0.0.0:7080"
        - name: CODER_ENVPROXY_ACCESS_URL
          value: "http://localhost:7080"
        ports:
        - containerPort: 7080
      serviceAccountName: coder-admin
