name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "petar_sandbox" branch
  push:
    branches: [ "petar_sandbox" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/minimal-hello:latest

      # Optionally run Docker image (example here runs it as a daemon)
      - name: Run Docker image
        run: |
          docker run -d --name my-running-app ghcr.io/${{ github.repository_owner }}/minimal-hello:latest

      # Additional commands to interact with your container
      - name: Check running containers
        run: docker ps

