name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main, dev ]  # Trigger the workflow on push to the main branch
  pull_request:
    branches: [ main, dev ]  # Trigger the workflow on pull requests targeting the main branch
  workflow_dispatch:    # Allow manual trigger of the workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: coder-ood

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repo name
      run: echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build the Docker image using docker-compose
      run: |
        docker-compose -f docker-compose.yml build
    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker-compose -f docker-compose.yml push app
    - name: Verify the image
      run: |
        docker pull ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/${{ env.IMAGE_NAME }}:latest
        docker run --rm -d -p 5050:5000 --name test_container ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/${{ env.IMAGE_NAME }}:latest
        sleep 10
        docker logs test_container
        # Include any tests you want to perform here
        docker stop test_container