name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]  # Trigger the workflow on push to the main branch
  pull_request:
    branches: [ main ]  # Trigger the workflow on pull requests targeting the main branch
  workflow_dispatch:    # Allow manual trigger of the workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hello-world
  TAG: terraform-deployment-automation
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Specifies the build context directory
        file: ./Dockerfile  # Path to the Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.TAG }}/${{ env.IMAGE_NAME }}:latest  # Replace with your desired image name

    - name: Verify the image
      run: |
        docker pull ${{ env.REGISTRY }}/${{ env.TAG }}/${{ env.IMAGE_NAME }}:latest
        docker run --rm ${{ env.REGISTRY }}/${{ env.TAG }}/${{ env.IMAGE_NAME }}:latest
