name: Deploy and Test Helm Charts

on: [push, pull_request]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.4

    - name: Create Kubernetes cluster
      run: kind create cluster --name test-cluster

    - name: Helm Install
      run: helm install mychart ./manifests/mychart

    - name: Wait for Kubernetes resources to be ready
      run: |
        kubectl wait --for=condition=available --timeout=600s deployment --all
        kubectl get all

    - name: Run Integration Tests
      run: |
        # Example integration test commands
        # Replace these with your actual integration test commands
        kubectl get pods
        kubectl get services
        # You can add curl or other commands to test the endpoints
        # For example:
        # POD_NAME=$(kubectl get pods -l app=mychart -o jsonpath="{.items[0].metadata.name}")
        # kubectl exec $POD_NAME -- curl -f http://localhost:8080/healthz

    - name: Delete Kubernetes cluster
      run: kind delete cluster --name test-cluster
