name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0' 

    - name: Terraform Init
      run: terraform init
      env:
        OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
        OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
        OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
